class AppResources {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'role': 'Senior Fullstack Developer',
      'hello': 'Hello There!',
      'intro': 'I am a Mobile & Backend Expert based in Vietnam. Specializing in high-performance apps with Flutter, SwiftUI & Spring Boot.',
      'btn_cv': 'Download CV',
      'section_skills': 'My Skills',
      'section_exp': 'Experience',
      'section_edu': 'Education',
      'section_pricing': 'Flexible Pricing',
      'section_services': 'Services I Provide',
      'contact_title': 'Get in Touch',
      'menu_home': 'Home',
      'menu_skills': 'Skills',
      'menu_services': 'Services',
      'menu_contact': 'Contact',
      'price_basic': 'Basic Plan',
      'price_std': 'Standard Plan',
      'price_premium': 'Custom Plan',
      'skill_fe': 'Frontend',
      'skill_be': 'Backend',
      'skill_fw': 'Frameworks',
      'skill_db': 'Database',
      'skill_tools': 'Tools',
      'skill_vc': 'Version Control',
      'section_projects': 'Projects',
      'view_project': 'View Details',
      'overview': 'Overview',
      'platforms': 'Platforms',
      'technologies': 'Technologies',
      'responsibilities': 'Responsibilities',
      'flutter_highlights': 'Flutter-specific highlights',
      'flutter_tech': 'Flutter-related tech',
      'team': 'Team',
      // contact form
      'contact_name_hint': 'Your name',
      'contact_email_hint': 'Your email',
      'contact_message_hint': 'Write your message...',
      'contact_send': 'Send Message',
      'contact_sending': 'Sending...',
      'contact_success': 'Message ready in your mail app. Please send to complete.',
      'contact_error': 'Unable to open mail app. Please try again.',

      // subscription / in-app strings
      'in_app_purchases_title': 'In-App Purchases & Subscriptions',
      'available_plans': 'Available plans',
      'billing_providers': 'Billing providers',
      'health_integrations': 'Health integrations',
      'buy': 'Buy',
      'purchase_for': 'Purchase:',
    },
    'vi': {
      'role': 'Senior Fullstack Developer',
      'hello': 'Xin chào!',
      'intro': 'Tôi là Chuyên gia Mobile & Backend tại Việt Nam. Chuyên xây dựng ứng dụng hiệu năng cao với Flutter, SwiftUI & Spring Boot.',
      'btn_cv': 'Tải CV',
      'section_skills': 'Kỹ Năng',
      'section_exp': 'Kinh Nghiệm',
      'section_edu': 'Học Vấn',
      'section_pricing': 'Bảng Giá Dịch Vụ',
      'section_services': 'Dịch Vụ Cung Cấp',
      'contact_title': 'Liên Hệ Ngay',
      'menu_home': 'Trang Chủ',
      'menu_skills': 'Kỹ Năng',
      'menu_services': 'Dịch Vụ',
      'menu_contact': 'Liên Hệ',
      'price_basic': 'Cơ Bản',
      'price_std': 'Tiêu Chuẩn',
      'price_pre': "Thỏa Thuận",
      'skill_fe': 'Frontend',
      'skill_be': 'Backend',
      'skill_fw': 'Frameworks',
      'skill_db': 'Cơ Sở Dữ Liệu',
      'skill_tools': 'Công Cụ',
      'skill_vc': 'Quản Lý Mã Nguồn',
      'section_projects': 'Dự Án',
      'view_project': 'Xem Chi Tiết',
      'overview': 'Tổng quan',
      'platforms': 'Nền tảng',
      'technologies': 'Công nghệ',
      'responsibilities': 'Trách nhiệm',
      'flutter_highlights': 'Điểm nổi bật về Flutter',
      'flutter_tech': 'Công nghệ liên quan Flutter',
      'team': 'Nhóm',
      // contact form
      'contact_name_hint': 'Tên của bạn',
      'contact_email_hint': 'Email của bạn',
      'contact_message_hint': 'Viết tin nhắn...',
      'contact_send': 'Gửi tin nhắn',
      'contact_sending': 'Đang gửi...',
      'contact_success': 'Tin nhắn đã sẵn sàng trong ứng dụng mail. Vui lòng gửi để hoàn tất.',
      'contact_error': 'Không thể mở ứng dụng mail. Vui lòng thử lại.',

      // subscription / in-app strings
      'in_app_purchases_title': 'Mua trong ứng dụng & Đăng ký',
      'available_plans': 'Các gói',
      'billing_providers': 'Nhà cung cấp thanh toán',
      'health_integrations': 'Tích hợp sức khỏe',
      'buy': 'Mua',
      'purchase_for': 'Mua:',
    }
  };

  static String getString(String langCode, String key) {
    return localizedValues[langCode]?[key] ?? key;
  }
}
